export const ALUNOS = [
  { id: 1, nome: 'Nicole Araújo', idade: 19, curso: 'Moda' },
  { id: 2, nome: 'Bruno Cardoso', idade: 23, curso: 'Engenharia de Produção' },
  { id: 3, nome: 'Luana Farias', idade: 21, curso: 'Psicologia' },
  { id: 4, nome: 'Henrique Barbosa', idade: 22, curso: 'Arquitetura' },
  { id: 5, nome: 'Letícia Martins', idade: 20, curso: 'Publicidade e Propaganda' },
  { id: 6, nome: 'Pedro Henrique', idade: 25, curso: 'Direito' },
  { id: 7, nome: 'Aline Costa', idade: 23, curso: 'Medicina' },
  { id: 8, nome: 'Matheus Gonçalves', idade: 19, curso: 'Ciências Contábeis' },
  { id: 9, nome: 'Raquel Teixeira', idade: 21, curso: 'Serviço Social' },
  { id: 10, nome: 'Caio Ribeiro', idade: 20, curso: 'Fisioterapia' },
  { id: 11, nome: 'Sabrina Lopes', idade: 22, curso: 'Engenharia Ambiental' },
  { id: 12, nome: 'Danilo Pires', idade: 24, curso: 'Sistemas de Informação' },
  { id: 13, nome: 'Helena Carvalho', idade: 19, curso: 'Biologia' },
  { id: 14, nome: 'Vinícius Andrade', idade: 23, curso: 'Administração' },
  { id: 15, nome: 'Talita Borges', idade: 20, curso: 'Química' },
  { id: 16, nome: 'Jonathan Cruz', idade: 21, curso: 'Engenharia de Computação' },
  { id: 17, nome: 'Yasmin Neves', idade: 22, curso: 'Farmácia' },
  { id: 18, nome: 'Marcelo Vieira', idade: 25, curso: 'Engenharia Civil' },
  { id: 19, nome: 'Elaine Martins', idade: 21, curso: 'Pedagogia' },
  { id: 20, nome: 'Samuel Dias', idade: 20, curso: 'Economia' },
  { id: 21, nome: 'Priscila Nogueira', idade: 22, curso: 'Letras' },
  { id: 22, nome: 'Rafael Tavares', idade: 23, curso: 'Geografia' },
  { id: 23, nome: 'Viviane Rocha', idade: 19, curso: 'Educação Física' },
  { id: 24, nome: 'Igor Martins', idade: 24, curso: 'Engenharia Química' },
  { id: 25, nome: 'Natália Freitas', idade: 20, curso: 'Relações Internacionais' },
  
  ];
  